In [1]:
!pip uninstall -y torch torchvision torchaudio
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install -U transformers peft accelerate bitsandbytes accelerate

Found existing installation: torch 2.10.0+cu128
Uninstalling torch-2.10.0+cu128:
  Successfully uninstalled torch-2.10.0+cu128
Found existing installation: torchvision 0.25.0+cu128
Uninstalling torchvision-0.25.0+cu128:
  Successfully uninstalled torchvision-0.25.0+cu128
Found existing installation: torchaudio 2.10.0+cu128
Uninstalling torchaudio-2.10.0+cu128:
  Successfully uninstalled torchaudio-2.10.0+cu128
Looking in indexes: https://download.pytorch.org/whl/cu121
Collecting torch
  Downloading https://download.pytorch.org/whl/cu121/torch-2.5.1%2Bcu121-cp312-cp312-linux_x86_64.whl (780.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 780.4/780.4 MB 1.9 MB/s eta 0:00:00
Collecting torchvision
  Downloading https://download-r2.pytorch.org/whl/cu121/torchvision-0.20.1%2Bcu121-cp312-cp312-linux_x86_64.whl (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 76.4 MB/s eta 0:00:00
Collecting torchaudio
  Downloading https://download-r2.pytorch.org/whl/cu121/torchaudio-2.5.1%2Bcu121-cp312-cp312-linux_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 112.8 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.25.2)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 81.2 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 56.7 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 91.8 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 812.7 kB/s eta 0:00:00
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.3 MB/s eta 0:00:00
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 8.3 MB/s eta 0:00:00
Collecting nvidia-curand-cu12==10.3.2.106 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 15.0 MB/s eta 0:00:00
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 8.4 MB/s eta 0:00:00
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 4.8 MB/s eta 0:00:00
Collecting nvidia-nccl-cu12==2.21.5 (from torch)
  Downloading https://download.pytorch.org/whl/nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 6.4 MB/s eta 0:00:00
Collecting nvidia-nvtx-cu12==12.1.105 (from torch)
  Downloading https://download.pytorch.org/whl/cu121/nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 10.1 MB/s eta 0:00:00
Collecting triton==3.1.0 (from torch)
  Downloading https://download-r2.pytorch.org/whl/triton-3.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (209.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.6/209.6 MB 5.7 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Collecting sympy==1.13.1 (from torch)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch) (12.8.93)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 72.9 MB/s eta 0:00:00
Installing collected packages: triton, sympy, nvidia-nvtx-cu12, nvidia-nccl-cu12, nvidia-cusparse-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusolver-cu12, nvidia-cudnn-cu12, torch, torchvision, torchaudio
  Attempting uninstall: triton
    Found existing installation: triton 3.6.0
    Uninstalling triton-3.6.0:
      Successfully uninstalled triton-3.6.0
  Attempting uninstall: sympy
    Found existing installation: sympy 1.14.0
    Uninstalling sympy-1.14.0:
      Successfully uninstalled sympy-1.14.0
  Attempting uninstall: nvidia-nvtx-cu12
    Found existing installation: nvidia-nvtx-cu12 12.8.90
    Uninstalling nvidia-nvtx-cu12-12.8.90:
      Successfully uninstalled nvidia-nvtx-cu12-12.8.90
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.27.5
    Uninstalling nvidia-nccl-cu12-2.27.5:
      Successfully uninstalled nvidia-nccl-cu12-2.27.5
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.8.93
    Uninstalling nvidia-cusparse-cu12-12.5.8.93:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.8.93
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.9.90
    Uninstalling nvidia-curand-cu12-10.3.9.90:
      Successfully uninstalled nvidia-curand-cu12-10.3.9.90
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.3.3.83
    Uninstalling nvidia-cufft-cu12-11.3.3.83:
      Successfully uninstalled nvidia-cufft-cu12-11.3.3.83
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.8.90
    Uninstalling nvidia-cuda-runtime-cu12-12.8.90:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.8.90
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.8.93
    Uninstalling nvidia-cuda-nvrtc-cu12-12.8.93:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.8.93
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.8.90
    Uninstalling nvidia-cuda-cupti-cu12-12.8.90:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.8.90
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.8.4.1
    Uninstalling nvidia-cublas-cu12-12.8.4.1:
      Successfully uninstalled nvidia-cublas-cu12-12.8.4.1
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.7.3.90
    Uninstalling nvidia-cusolver-cu12-11.7.3.90:
      Successfully uninstalled nvidia-cusolver-cu12-11.7.3.90
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.10.2.21
    Uninstalling nvidia-cudnn-cu12-9.10.2.21:
      Successfully uninstalled nvidia-cudnn-cu12-9.10.2.21
Successfully installed nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.21.5 nvidia-nvtx-cu12-12.1.105 sympy-1.13.1 torch-2.5.1+cu121 torchaudio-2.5.1+cu121 torchvision-0.20.1+cu121 triton-3.1.0
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.5.1+cu121)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.1.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.12/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.5.0-py3-none-any.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 99.9 MB/s eta 0:00:00
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 12.9 MB/s eta 0:00:00
Installing collected packages: bitsandbytes, transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed bitsandbytes-0.49.2 transformers-5.5.0

In [1]:
import pandas as pd

def split(csv_path, train_ratio=0.6, val_ratio=0.2):
    df = pd.read_csv(csv_path)
    df = df.sort_values("Timestamp").reset_index(drop=True)
    n = len(df)
    train_end = int(n * train_ratio)
    val_end = int(n * (train_ratio + val_ratio))
    train_df = df.iloc[:train_end]
    val_df = df.iloc[train_end:val_end]
    test_df = df.iloc[val_end:]
    return df,train_df, val_df, test_df

In [2]:
import pandas as pd
import numpy as np
from torch.utils.data import Dataset, DataLoader
import torch

df,train_df,val_df,test_df = split("/content/BGL_1000k_log_structured_cleaned.csv")
id_to_template = dict(zip(df["EventId"], df["EventTemplate"]))
special_tokens = ["[PAD]", "[CLS]", "[MASK]", "[UNK]"]
event_ids = df["EventId"].unique().tolist()

event2id = {token: i for i, token in enumerate(special_tokens)}
for i, eid in enumerate(event_ids):
    event2id[eid] = i + len(special_tokens)

id2event = {v: k for k, v in event2id.items()}
vocab_size = len(event2id)

print(f"Vocab Size: {vocab_size}")

train_df.head()

Vocab Size: 242

,LineId,Label,Timestamp,Date,Node,Time,NodeRepeat,Type,Component,Level,Content,EventId,EventTemplate
0,4,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.823719,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,E1,instruction cache parity error corrected
1,2,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.527847,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,E1,instruction cache parity error corrected
2,3,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.675872,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,E1,instruction cache parity error corrected
3,1,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.363779,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,E1,instruction cache parity error corrected
4,5,-,1117838570,2005.06.03,R02-M1-N0-C:J12-U11,2005-06-03-15.42.50.982731,R02-M1-N0-C:J12-U11,RAS,KERNEL,INFO,instruction cache parity error corrected,E1,instruction cache parity error corrected

In [3]:
id_to_template = dict(zip(df["EventId"], df["EventTemplate"]))

In [ ]:
id2event = {v: k for k, v in event2id.items()}

In [4]:
import torch
import pandas as pd
from torch.utils.data import DataLoader
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
WINDOW_SIZE = 128
BATCH_SIZE = 128
EPOCHS = 50
STEP_SIZE = 32

In [5]:
import pandas as pd
from tqdm import tqdm
def generate_sequences(df, window_size, step_size, min_anomaly_check=True):
    df_sorted = df.sort_values("Timestamp").reset_index(drop=True)
    event_ids = df_sorted["EventId"].values
    labels = df_sorted["Label"].values
    sequences  = []
    seq_labels = []
    for i in range(0, len(event_ids) - window_size, step_size):
        seq = event_ids[i : i + window_size].tolist()
        is_anomaly = int(any(l != '-' and l != 0 for l in labels[i : i + window_size]))
        sequences.append(seq)
        seq_labels.append(is_anomaly)

    return sequences, seq_labels

In [6]:
class LogDataset(Dataset):
    def __init__(self, sequences, event2id, seq_labels, mask_ratio=0.15):
        self.sequences  = sequences
        self.event2id   = event2id
        self.labels     = seq_labels
        self.mask_ratio = mask_ratio
    def __len__(self):
        return len(self.sequences)
    def __getitem__(self, idx):
        line    = self.sequences[idx]
        encoded = [self.event2id.get(eid, self.event2id["[UNK]"]) for eid in line]
        tokens  = [self.event2id["[CLS]"]] + encoded
        input_ids    = []
        output_label = []
        for i, token in enumerate(tokens):
            if i == 0:
                input_ids.append(token)
                output_label.append(-100)
                continue
            if np.random.random() < self.mask_ratio:
                p = np.random.random()
                if p < 0.80:
                    input_ids.append(self.event2id["[MASK]"])
                elif p < 0.90:
                    input_ids.append(np.random.randint(
                        len(special_tokens), len(self.event2id)))
                else:
                    input_ids.append(token)
                output_label.append(token)
            else:
                input_ids.append(token)
                output_label.append(-100)
        return (
            torch.tensor(input_ids),
            torch.tensor(output_label),
            torch.tensor(tokens),
        )

In [7]:
all_seqs, all_labels = generate_sequences(df, WINDOW_SIZE, STEP_SIZE)
n = len(all_seqs)
train_end = int(n * 0.6)
val_end = int(n * 0.8)

train_seqs = all_seqs[:train_end]
train_labels = all_labels[:train_end]
val_seqs = all_seqs[train_end:val_end]
val_labels = all_labels[train_end:val_end]
test_seqs = all_seqs[val_end:]
test_gt = all_labels[val_end:]

train_normal_seqs = [s for s, l in zip(train_seqs, train_labels) if l == 0]
val_normal_seqs = [s for s, l in zip(val_seqs,   val_labels)   if l == 0]

train_dataset = LogDataset(train_normal_seqs,event2id, [],mask_ratio=0.15)
val_dataset = LogDataset(val_normal_seqs,event2id, [],mask_ratio=0.15)
test_dataset = LogDataset(test_seqs,event2id, test_gt,mask_ratio=0.15)

train_loader  = DataLoader(train_dataset, batch_size=128, shuffle=True)
val_loader = DataLoader(val_dataset,   batch_size=128, shuffle=False)
test_loader = DataLoader(test_dataset,  batch_size=128, shuffle=False)

print(f"test_gt length      : {len(test_gt)}")
print(f"test_dataset length : {len(test_dataset)}")
print(f"test_loader batches : {len(test_loader)}")

test_gt length      : 6250
test_dataset length : 6250
test_loader batches : 49

In [8]:
import torch
import torch.nn as nn
class LogBERT(nn.Module):
    def __init__(self, vocab_size, hidden_size=256, num_layers=2,
                 num_heads=4, max_len=514, dropout=0.3):
        super().__init__()
        self.hidden_size = hidden_size
        self.embedding     = nn.Embedding(vocab_size, hidden_size)
        self.pos_embedding = nn.Parameter(
            torch.randn(1, max_len, hidden_size) * 0.02
        )
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=hidden_size, nhead=num_heads,
            batch_first=True, dropout=dropout,
            dim_feedforward=128
        )
        self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.mask_lm = nn.Linear(hidden_size, vocab_size)
        self._init_weights()
    def _init_weights(self):
        for module in self.modules():
            if isinstance(module, nn.Linear):
                nn.init.xavier_uniform_(module.weight)
                if module.bias is not None:
                    nn.init.zeros_(module.bias)
            elif isinstance(module, nn.Embedding):
                nn.init.normal_(module.weight, mean=0, std=0.02)
    def forward(self, x):
        b, seq_len = x.size()
        x       = self.embedding(x) + self.pos_embedding[:, :seq_len, :]
        encoded = self.encoder(x)
        logits  = self.mask_lm(encoded)
        cls_emb = encoded[:, 0, :]
        return logits, cls_emb

In [9]:
model = LogBERT(len(event2id), hidden_size=256, num_layers=2,
                    num_heads=4, max_len=514).to(DEVICE)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4, weight_decay=1e-5)
criterion = torch.nn.CrossEntropyLoss(ignore_index=-100)
print(f"\nModel parameters : {sum(p.numel() for p in model.parameters()):,}")

Model parameters : 915,954

In [10]:
from tqdm import tqdm
import math
alpha        = 0.0
best_val_loss = float('inf')
WARMUP    = 2
def get_lr_scale(epoch, warmup_epochs=WARMUP):
    if epoch < warmup_epochs:
        return (epoch + 1) / warmup_epochs
    progress = (epoch - warmup_epochs) / max(1, EPOCHS - warmup_epochs)
    return 0.1 + 0.9 * 0.5 * (1 + math.cos(math.pi * progress))
scheduler     = torch.optim.lr_scheduler.LambdaLR(optimizer, get_lr_scale)
best_val_loss = float('inf')
for epoch in tqdm(range(EPOCHS)):
    model.train()
    train_loss = 0.0
    total_masked = 0
    total_correct = 0
    for x, y, _ in train_loader:
        x, y = x.to(DEVICE), y.to(DEVICE)
        logits, _ = model(x)
        loss = criterion(logits.view(-1, logits.size(-1)), y.view(-1))

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=0.5)
        optimizer.step()
        train_loss += loss.item()
        with torch.no_grad():
            mask = y != -100
            preds = logits.argmax(dim=-1)
            correct = (preds[mask] == y[mask]).sum().item()
            total_correct += correct
            total_masked  += mask.sum().item()

    scheduler.step()
    train_acc = total_correct / total_masked * 100 if total_masked > 0 else 0
    model.eval()
    val_loss    = 0.0
    val_masked  = 0
    val_correct = 0

    with torch.no_grad():
        for x, y, _ in val_loader:
            x, y  = x.to(DEVICE), y.to(DEVICE)
            logits, _ = model(x)
            val_loss += criterion(
                logits.view(-1, logits.size(-1)), y.view(-1)).item()

            mask = y != -100
            preds = logits.argmax(dim=-1)
            val_correct += (preds[mask] == y[mask]).sum().item()
            val_masked  += mask.sum().item()

    avg_train = train_loss  / len(train_loader)
    avg_val = val_loss    / len(val_loader)
    val_acc = val_correct / val_masked * 100 if val_masked > 0 else 0
    lr_now  = optimizer.param_groups[0]['lr']
    print(f"Epoch {epoch+1:02d} | "
          f"Train Loss: {avg_train:.4f} Acc: {train_acc:.1f}% | "
          f"Val Loss: {avg_val:.4f} Acc: {val_acc:.1f}% | "
          f"LR: {lr_now:.6f}")

    if avg_val < best_val_loss:
        best_val_loss = avg_val
        torch.save(model.state_dict(), "fn_logbert.pt")
        print(f"Best model saved")

  2%|▏         | 1/50 [00:07<06:29,  7.94s/it]

Epoch 01 | Train Loss: 2.0399 Acc: 65.1% | Val Loss: 4.5791 Acc: 24.2% | LR: 0.000100
Best model saved

  4%|▍         | 2/50 [00:15<06:16,  7.85s/it]

Epoch 02 | Train Loss: 0.3631 Acc: 88.6% | Val Loss: 4.0857 Acc: 34.2% | LR: 0.000100
Best model saved

  6%|▌         | 3/50 [00:24<06:19,  8.08s/it]

Epoch 03 | Train Loss: 0.2681 Acc: 89.0% | Val Loss: 3.5584 Acc: 39.6% | LR: 0.000100
Best model saved

  8%|▊         | 4/50 [00:31<06:07,  7.99s/it]

Epoch 04 | Train Loss: 0.2411 Acc: 89.4% | Val Loss: 3.1428 Acc: 42.9% | LR: 0.000100
Best model saved

 10%|█         | 5/50 [00:39<05:58,  7.97s/it]

Epoch 05 | Train Loss: 0.2290 Acc: 89.5% | Val Loss: 2.8689 Acc: 47.6% | LR: 0.000099
Best model saved

 12%|█▏        | 6/50 [00:48<05:55,  8.07s/it]

Epoch 06 | Train Loss: 0.2197 Acc: 89.5% | Val Loss: 2.6931 Acc: 50.6% | LR: 0.000098
Best model saved

 14%|█▍        | 7/50 [00:55<05:39,  7.90s/it]

Epoch 07 | Train Loss: 0.2140 Acc: 89.6% | Val Loss: 2.6118 Acc: 53.3% | LR: 0.000098
Best model saved

 16%|█▌        | 8/50 [01:03<05:33,  7.95s/it]

Epoch 08 | Train Loss: 0.2086 Acc: 89.6% | Val Loss: 2.5156 Acc: 55.0% | LR: 0.000097
Best model saved

 18%|█▊        | 9/50 [01:13<05:53,  8.61s/it]

Epoch 09 | Train Loss: 0.2055 Acc: 89.6% | Val Loss: 2.4425 Acc: 56.2% | LR: 0.000095
Best model saved

 20%|██        | 10/50 [01:21<05:32,  8.30s/it]

Epoch 10 | Train Loss: 0.2042 Acc: 89.6% | Val Loss: 2.3912 Acc: 56.5% | LR: 0.000094
Best model saved

 22%|██▏       | 11/50 [01:33<06:07,  9.43s/it]

Epoch 11 | Train Loss: 0.2036 Acc: 89.5% | Val Loss: 2.2979 Acc: 58.2% | LR: 0.000092
Best model saved

 24%|██▍       | 12/50 [01:41<05:43,  9.03s/it]

Epoch 12 | Train Loss: 0.2006 Acc: 89.6% | Val Loss: 2.3046 Acc: 58.7% | LR: 0.000091

 26%|██▌       | 13/50 [01:49<05:23,  8.74s/it]

Epoch 13 | Train Loss: 0.1995 Acc: 89.6% | Val Loss: 2.2379 Acc: 60.3% | LR: 0.000089
Best model saved

 28%|██▊       | 14/50 [01:57<05:06,  8.51s/it]

Epoch 14 | Train Loss: 0.1971 Acc: 89.7% | Val Loss: 2.2535 Acc: 60.0% | LR: 0.000087

 30%|███       | 15/50 [02:05<04:54,  8.42s/it]

Epoch 15 | Train Loss: 0.1972 Acc: 89.6% | Val Loss: 2.2139 Acc: 61.9% | LR: 0.000085
Best model saved

 32%|███▏      | 16/50 [02:13<04:38,  8.20s/it]

Epoch 16 | Train Loss: 0.1932 Acc: 89.8% | Val Loss: 2.2015 Acc: 61.1% | LR: 0.000082
Best model saved

 34%|███▍      | 17/50 [02:21<04:29,  8.17s/it]

Epoch 17 | Train Loss: 0.1933 Acc: 89.7% | Val Loss: 2.1937 Acc: 61.1% | LR: 0.000080
Best model saved

 36%|███▌      | 18/50 [02:29<04:22,  8.21s/it]

Epoch 18 | Train Loss: 0.1925 Acc: 89.8% | Val Loss: 2.1767 Acc: 61.7% | LR: 0.000077
Best model saved

 38%|███▊      | 19/50 [02:37<04:08,  8.03s/it]

Epoch 19 | Train Loss: 0.1911 Acc: 89.8% | Val Loss: 2.1608 Acc: 61.4% | LR: 0.000075
Best model saved

 40%|████      | 20/50 [02:45<04:01,  8.05s/it]

Epoch 20 | Train Loss: 0.1907 Acc: 89.8% | Val Loss: 2.1319 Acc: 62.3% | LR: 0.000072
Best model saved

 42%|████▏     | 21/50 [02:54<03:57,  8.19s/it]

Epoch 21 | Train Loss: 0.1918 Acc: 89.7% | Val Loss: 2.1513 Acc: 61.6% | LR: 0.000069

 44%|████▍     | 22/50 [03:01<03:44,  8.01s/it]

Epoch 22 | Train Loss: 0.1887 Acc: 89.8% | Val Loss: 2.1433 Acc: 62.1% | LR: 0.000067

 46%|████▌     | 23/50 [03:09<03:37,  8.04s/it]

Epoch 23 | Train Loss: 0.1827 Acc: 90.1% | Val Loss: 2.1422 Acc: 62.0% | LR: 0.000064

 48%|████▊     | 24/50 [03:18<03:32,  8.18s/it]

Epoch 24 | Train Loss: 0.1823 Acc: 90.0% | Val Loss: 2.1343 Acc: 62.9% | LR: 0.000061

 50%|█████     | 25/50 [03:26<03:21,  8.07s/it]

Epoch 25 | Train Loss: 0.1794 Acc: 90.2% | Val Loss: 2.1066 Acc: 63.2% | LR: 0.000058
Best model saved

 52%|█████▏    | 26/50 [03:34<03:13,  8.08s/it]

Epoch 26 | Train Loss: 0.1784 Acc: 90.1% | Val Loss: 2.1020 Acc: 63.4% | LR: 0.000055
Best model saved

 54%|█████▍    | 27/50 [03:42<03:05,  8.08s/it]

Epoch 27 | Train Loss: 0.1778 Acc: 90.2% | Val Loss: 2.0938 Acc: 63.1% | LR: 0.000052
Best model saved

 56%|█████▌    | 28/50 [03:50<02:56,  8.02s/it]

Epoch 28 | Train Loss: 0.1743 Acc: 90.4% | Val Loss: 2.0788 Acc: 63.5% | LR: 0.000049
Best model saved

 58%|█████▊    | 29/50 [03:58<02:48,  8.02s/it]

Epoch 29 | Train Loss: 0.1753 Acc: 90.3% | Val Loss: 2.0934 Acc: 63.2% | LR: 0.000046

 60%|██████    | 30/50 [04:05<02:37,  7.89s/it]

Epoch 30 | Train Loss: 0.1740 Acc: 90.3% | Val Loss: 2.0636 Acc: 63.4% | LR: 0.000043
Best model saved

 62%|██████▏   | 31/50 [04:13<02:31,  7.95s/it]

Epoch 31 | Train Loss: 0.1741 Acc: 90.3% | Val Loss: 2.0612 Acc: 63.2% | LR: 0.000041
Best model saved

 64%|██████▍   | 32/50 [04:22<02:24,  8.03s/it]

Epoch 32 | Train Loss: 0.1719 Acc: 90.4% | Val Loss: 2.0774 Acc: 63.4% | LR: 0.000038

 66%|██████▌   | 33/50 [04:29<02:14,  7.89s/it]

Epoch 33 | Train Loss: 0.1709 Acc: 90.4% | Val Loss: 2.0653 Acc: 63.9% | LR: 0.000035

 68%|██████▊   | 34/50 [04:37<02:06,  7.93s/it]

Epoch 34 | Train Loss: 0.1706 Acc: 90.4% | Val Loss: 2.0648 Acc: 64.0% | LR: 0.000033

 70%|███████   | 35/50 [04:46<02:01,  8.13s/it]

Epoch 35 | Train Loss: 0.1705 Acc: 90.3% | Val Loss: 2.0236 Acc: 64.3% | LR: 0.000030
Best model saved

 72%|███████▏  | 36/50 [04:53<01:51,  7.96s/it]

Epoch 36 | Train Loss: 0.1698 Acc: 90.4% | Val Loss: 2.0504 Acc: 64.2% | LR: 0.000028

 74%|███████▍  | 37/50 [05:01<01:43,  7.99s/it]

Epoch 37 | Train Loss: 0.1714 Acc: 90.3% | Val Loss: 2.0374 Acc: 64.2% | LR: 0.000025

 76%|███████▌  | 38/50 [05:10<01:37,  8.09s/it]

Epoch 38 | Train Loss: 0.1696 Acc: 90.5% | Val Loss: 2.0491 Acc: 64.4% | LR: 0.000023

 78%|███████▊  | 39/50 [05:18<01:28,  8.01s/it]

Epoch 39 | Train Loss: 0.1681 Acc: 90.5% | Val Loss: 2.0590 Acc: 64.2% | LR: 0.000021

 80%|████████  | 40/50 [05:26<01:20,  8.04s/it]

Epoch 40 | Train Loss: 0.1695 Acc: 90.4% | Val Loss: 2.0560 Acc: 64.7% | LR: 0.000019

 82%|████████▏ | 41/50 [05:34<01:11,  7.99s/it]

Epoch 41 | Train Loss: 0.1665 Acc: 90.5% | Val Loss: 2.0541 Acc: 64.6% | LR: 0.000018

 84%|████████▍ | 42/50 [05:42<01:03,  7.99s/it]

Epoch 42 | Train Loss: 0.1681 Acc: 90.5% | Val Loss: 2.0466 Acc: 64.5% | LR: 0.000016

 86%|████████▌ | 43/50 [05:50<00:56,  8.02s/it]

Epoch 43 | Train Loss: 0.1674 Acc: 90.4% | Val Loss: 2.0541 Acc: 64.6% | LR: 0.000015

 88%|████████▊ | 44/50 [05:57<00:47,  7.90s/it]

Epoch 44 | Train Loss: 0.1673 Acc: 90.4% | Val Loss: 2.0552 Acc: 64.5% | LR: 0.000013

 90%|█████████ | 45/50 [06:05<00:39,  7.95s/it]

Epoch 45 | Train Loss: 0.1696 Acc: 90.5% | Val Loss: 2.0571 Acc: 64.4% | LR: 0.000012

 92%|█████████▏| 46/50 [06:14<00:32,  8.07s/it]

Epoch 46 | Train Loss: 0.1678 Acc: 90.5% | Val Loss: 2.0521 Acc: 64.6% | LR: 0.000012

 94%|█████████▍| 47/50 [06:21<00:23,  7.94s/it]

Epoch 47 | Train Loss: 0.1674 Acc: 90.5% | Val Loss: 2.0641 Acc: 64.5% | LR: 0.000011

 96%|█████████▌| 48/50 [06:29<00:15,  8.00s/it]

Epoch 48 | Train Loss: 0.1682 Acc: 90.4% | Val Loss: 2.0447 Acc: 64.6% | LR: 0.000010

 98%|█████████▊| 49/50 [06:38<00:08,  8.19s/it]

Epoch 49 | Train Loss: 0.1666 Acc: 90.5% | Val Loss: 2.0344 Acc: 64.7% | LR: 0.000010

100%|██████████| 50/50 [06:46<00:00,  8.12s/it]

Epoch 50 | Train Loss: 0.1680 Acc: 90.5% | Val Loss: 2.0590 Acc: 64.4% | LR: 0.000010

In [11]:
model_test = LogBERT(len(event2id), hidden_size=256, num_layers=2,
                     num_heads=4, max_len=514).to(DEVICE)
model_test.load_state_dict(torch.load("fn_logbert.pt", weights_only=True))
model_test.eval()

LogBERT(
  (embedding): Embedding(242, 256)
  (encoder): TransformerEncoder(
    (layers): ModuleList(
      (0-1): 2 x TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=256, out_features=256, bias=True)
        )
        (linear1): Linear(in_features=256, out_features=128, bias=True)
        (dropout): Dropout(p=0.3, inplace=False)
        (linear2): Linear(in_features=128, out_features=256, bias=True)
        (norm1): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (norm2): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
        (dropout1): Dropout(p=0.3, inplace=False)
        (dropout2): Dropout(p=0.3, inplace=False)
      )
    )
  )
  (mask_lm): Linear(in_features=256, out_features=242, bias=True)
)

In [ ]:
print("Test sequences:", len(test_dataset))
print("Test batches:", len(test_loader))

In [ ]:
from sklearn.metrics import f1_score
import numpy as np

g_candidates = [3, 5, 9, 15, 20]
val_counts_by_g = {}
model_test.eval()
with torch.no_grad():
    for g_val in g_candidates:
        val_counts = []

        for x, y, original_ids in val_loader:
            x = x.to(DEVICE)
            logits, _ = model_test(x)
            probs = torch.softmax(logits, dim=-1)
            top_g_idx = torch.topk(probs, g_val, dim=-1).indices.cpu()
            y_cpu = y.cpu()
            orig_cpu = original_ids.cpu()

            for i in range(x.size(0)):
                wrong = 0
                total_masked = 0
                for j in range(1, y_cpu[i].size(0)):
                    if y_cpu[i][j].item() == -100:
                        continue
                    total_masked += 1
                    if orig_cpu[i][j].item() not in top_g_idx[i, j].tolist():
                        wrong += 1
                val_counts.append(wrong)

        val_counts_by_g[g_val] = np.array(val_counts)
print(f"\n{'g':>4} | wrong count distribution on val (all normal)")
print(f"{'':>4}   50th  90th  95th  99th  → chosen r")
print("-" * 52)
chosen_r = {}
for g_val in g_candidates:
    counts   = val_counts_by_g[g_val]
    p50 = np.percentile(counts, 50)
    p90 = np.percentile(counts, 90)
    p95 = np.percentile(counts, 95)
    p99 = np.percentile(counts, 99)
    r_chosen = int(p99)
    chosen_r[g_val] = r_chosen
    print(f"g={g_val:>2} | {p50:>5.1f} {p90:>5.1f} {p95:>5.1f} {p99:>5.1f}  → r={r_chosen}")

   g | wrong count distribution on val (all normal)
       50th  90th  95th  99th  → chosen r
----------------------------------------------------
g= 3 |   0.0  10.0  12.0  15.0  → r=15
g= 5 |   0.0   9.0  12.0  15.0  → r=15
g= 9 |   0.0   9.0  11.0  15.0  → r=15
g=15 |   0.0   9.0  11.0  14.0  → r=14
g=20 |   0.0   8.0  11.0  14.0  → r=14

In [58]:
from sklearn.metrics import precision_score, recall_score, f1_score
import numpy as np
g = 5
r = 15
pred_labels = []
with torch.no_grad():
    for x, _, original_ids in test_loader:
        x = x.to(DEVICE)
        logits, _ = model_test(x)
        probs = torch.softmax(logits, dim=-1)
        top_g_idx = torch.topk(probs, g, dim=-1).indices.cpu()
        orig_cpu = original_ids.cpu()
        for i in range(x.size(0)):
            count = 0
            for j in range(1, orig_cpu[i].size(0)):
                if orig_cpu[i][j].item() not in top_g_idx[i, j].tolist():
                    count += 1
            pred_labels.append(1 if count > r else 0)
p   = precision_score(test_gt, pred_labels, zero_division=0)
r_  = recall_score(test_gt, pred_labels, zero_division=0)
f1  = f1_score(test_gt, pred_labels, zero_division=0)
print(f"Precision : {p:.4f}")
print(f"Recall    : {r_:.4f}")
print(f"F1        : {f1:.4f}")

Precision : 0.8794
Recall    : 0.8663
F1        : 0.8728

Proving val set is not distributed properly

In [56]:
print(f"Train anomaly rate: {sum(train_labels)/len(train_labels):.3f}")
print(f"Val anomaly rate  : {sum(val_labels)/len(val_labels):.3f}")
print(f"Test anomaly rate : {sum(test_gt)/len(test_gt):.3f}")

Train anomaly rate: 0.435
Val anomaly rate  : 0.021
Test anomaly rate : 0.032

In [21]:
anomalies    = []
g = 5
with torch.no_grad():
    for batch_idx, (x, y, original_ids) in enumerate(test_loader):
        x = x.to(DEVICE)
        logits, _ = model_test(x)
        probs = torch.softmax(logits, dim=-1)
        top_g_idx = torch.topk(probs, g, dim=-1).indices.cpu()
        y_cpu = y.cpu()
        orig_cpu = original_ids.cpu()
        for i in range(x.size(0)):
            wrong        = 0
            total_masked = 0
            for j in range(1, y_cpu[i].size(0)):
                if y_cpu[i][j].item() == -100:
                    continue
                total_masked += 1
                real_token    = orig_cpu[i][j].item()
                if real_token not in top_g_idx[i, j].tolist():
                    wrong += 1
            if total_masked == 0:
                continue

            global_seq_id  = batch_idx * test_loader.batch_size + i
            if wrong > r:
                orig_tokens = orig_cpu[i].tolist()
                event_ids   = [id2event[t] for t in orig_tokens if t not in (event2id["[CLS]"],event2id["[PAD]"])]
                anomalies.append({
                    "sequence_id"  : global_seq_id,
                    "anomaly_score": round(wrong, 4),
                    "events"       : event_ids
                })
print(f"Anomalies detected : {len(anomalies)}")

Anomalies detected : 100

In [22]:
for anomaly in anomalies:
    anomaly["events"] = [
        id_to_template[eid] for eid in anomaly["events"]
    ]

In [25]:
import json
with open("/content/anomalies5.json", "w") as f:
    json.dump(anomalies, f, indent=2)

In [29]:
def format_instruction(sample):
    instruction = "Analyze the following log sequence and determine if it is normal or abnormal. Provide a concise explanation for your judgment."
    input_text = f"Input: {sample['log_seq']}"
    output_text = f"Output: {sample['label-cause pair']}"
    return f"### Instruction:\n{instruction}\n\n### {input_text}\n\n### {output_text}"

In [27]:
from google.colab import userdata
secret_value_0 = userdata.get('HF_TOKEN')

In [28]:
import os
from huggingface_hub import login

login(secret_value_0)

### Fine Tuning LLMs

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model

In [30]:
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model

model_id = "meta-llama/Meta-Llama-3-8B"
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype="float16",
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=bnb_config, device_map="auto")
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, peft_config)

config.json:   0%|          | 0.00/654 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/177 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/73.0 [00:00<?, ?B/s]

In [31]:
from transformers import Trainer, TrainingArguments
import torch

In [32]:
import ast
with open('/content/seed_bgl.json', 'r') as f:
    raw_data = ast.literal_eval(f.read())
formatted_data = [format_instruction(item) for item in raw_data]
from datasets import Dataset
dataset = Dataset.from_dict({"text": formatted_data})
print(dataset[0]['text'])

### Instruction:
Analyze the following log sequence and determine if it is normal or abnormal. Provide a concise explanation for your judgment.

### Input: quiet <*>................................<*>,minus inf................................<*>,minus normalized number..................<*>,minus denormalized number................<*>,plus zero................................<*>,plus denormalized number.................<*>,plus normalized number...................<*>,plus infinity............................<*>,reserved.................................<*>,invalid operation exception (software)...<*>,invalid operation exception (sqrt).......<*>,invalid operation exception (int cnvt)...<*>,enable invalid operation exceptions......<*>,enable overflow exceptions...............<*>,enable underflow exceptions..............<*>,enable divide-by-zero exceptions.........<*>,enable inexact exceptions................<*>,enable non-IEEE mode.....................<*>,round nearest............................<*>,round toward zero...................<*>

### Output: normal-The log sequence is normal because it represents the normal behavior of a floating-point unit (FPU) in response to various operations and exceptions. The sequence covers various scenarios such as handling different types of numbers (normal, denormalized, infinity, zero), exceptions (invalid operations, overflow, underflow, divide-by-zero, inexact), and mode settings (invalid operation exceptions, IEEE mode, rounding modes).

In [33]:
def tokenize_function(examples):
    tokenized = tokenizer(
        examples["text"],
        truncation=True,
        max_length=512,
        padding="max_length"
    )
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized
tokenized_dataset = dataset.map(tokenize_function, batched=True)
tokenized_dataset = tokenized_dataset.remove_columns(["text"])

Map:   0%|          | 0/30 [00:00<?, ? examples/s]

In [34]:
import torch.nn as nn
class LLMLADELoss(nn.Module):
    def __init__(self, alpha=0.7, beta=0.3, gamma=2.0):
        super().__init__()
        self.alpha = alpha
        self.beta = beta
        self.gamma = gamma
        self.ce_loss = nn.CrossEntropyLoss(reduction='none')

    def forward(self, logits, labels):
        shift_logits = logits[..., :-1, :].contiguous()
        shift_labels = labels[..., 1:].contiguous()
        logits_flat = shift_logits.view(-1, shift_logits.size(-1))
        labels_flat = shift_labels.view(-1)
        raw_loss = self.ce_loss(logits_flat, labels_flat)
        probs = torch.softmax(logits_flat, dim=-1)
        pt = probs.gather(1, labels_flat.unsqueeze(1)).squeeze(1)
        focal_loss = (self.alpha * (1 - pt)**self.gamma * raw_loss)
        cause_loss = (self.beta * raw_loss)
        return focal_loss.mean() + cause_loss.mean()

In [35]:
class LLMLADETrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False,**kwargs):
        outputs = model(**inputs)
        logits = outputs.get("logits")
        labels = inputs.get("labels")

        loss_fct = LLMLADELoss(alpha=0.7, beta=0.3, gamma=2.0)
        loss = loss_fct(logits, labels)

        return (loss, outputs) if return_outputs else loss

In [36]:
training_args = TrainingArguments(
    output_dir="./llm_lade_results",
    num_train_epochs=10,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=5e-5,
    lr_scheduler_type="cosine",
    optim="adamw_torch",
    fp16=True,
    logging_steps=5,
)
trainer = LLMLADETrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset
)
trainer.train()

TrainOutput(global_step=40, training_loss=6.263241338729858, metrics={'train_runtime': 571.6902, 'train_samples_per_second': 0.525, 'train_steps_per_second': 0.07, 'total_flos': 6929101357056000.0, 'train_loss': 6.263241338729858, 'epoch': 10.0})

In [38]:
trainer.save_model("./llm_lade_results")

In [ ]:
!zip -r llm_lade_results.zip llm_lade_results

In [39]:
input_file = "/content/anomalies5.json"
output_file = "/content/llm_results.json"

In [40]:
import torch
import gc
if 'model' in locals(): del model
if 'base_model' in locals(): del base_model
if 'trainer' in locals(): del trainer
gc.collect()
torch.cuda.empty_cache()
free_memory = torch.cuda.get_device_properties(0).total_memory - torch.cuda.memory_allocated(0)
print(f"Free GPU memory: {free_memory / 1024**3:.2f} GB")

Free GPU memory: 14.49 GB

In [41]:
import torch
from peft import PeftModel
import os
base_model_path = "meta-llama/Meta-Llama-3-8B"
adapter_path = os.path.abspath("./llm_lade_results")
tokenizer = AutoTokenizer.from_pretrained(base_model_path)
tokenizer.pad_token = tokenizer.eos_token
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)
base_model = AutoModelForCausalLM.from_pretrained(
    "meta-llama/Meta-Llama-3-8B",
    quantization_config=bnb_config,
    device_map="auto"
)
model = PeftModel.from_pretrained(base_model, adapter_path)
model.eval()

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): LlamaForCausalLM(
      (model): LlamaModel(
        (embed_tokens): Embedding(128256, 4096)
        (layers): ModuleList(
          (0-31): 32 x LlamaDecoderLayer(
            (self_attn): LlamaAttention(
              (q_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (k_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (v_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=1024, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=1024, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
              (o_proj): lora.Linear4bit(
                (base_layer): Linear4bit(in_features=4096, out_features=4096, bias=False)
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.05, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
                (lora_magnitude_vector): ModuleDict()
              )
            )
            (mlp): LlamaMLP(
              (gate_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
              (up_proj): Linear4bit(in_features=4096, out_features=14336, bias=False)
              (down_proj): Linear4bit(in_features=14336, out_features=4096, bias=False)
              (act_fn): SiLUActivation()
            )
            (input_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
            (post_attention_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
          )
        )
        (norm): LlamaRMSNorm((4096,), eps=1e-05)
        (rotary_emb): LlamaRotaryEmbedding()
      )
      (lm_head): Linear(in_features=4096, out_features=128256, bias=False)
    )
  )
)

In [42]:
import json
with open(input_file, 'r') as f:
    anomalies = json.load(f)

In [43]:
from collections import Counter
def compress_sequence(events, max_unique=20, max_total=40):
    counts = Counter(events)
    compressed = []
    seen = set()
    for event in events:
        if event not in seen:
            seen.add(event)
            count = counts[event]
            if count > 1:
                compressed.append(f"[x{count}] {event}")
            else:
                compressed.append(event)
        if len(compressed) >= max_unique:
            break
    return compressed

In [46]:
from tqdm import tqdm
finals = []
with torch.inference_mode():
    for entry in tqdm(anomalies):
        seq = compress_sequence(entry['events'])
        log_seq_str = "\n".join(seq)
        instruction = (
            "Analyze the following log sequence. Determine if it is normal or abnormal. "
            "Provide a concise explanation of the root cause if abnormal, "
            "and suggest a specific, actionable solution to resolve the issue."
        )
        prompt = (
            f"### Instruction:\n{instruction}\n\n"
            f"### Input:\n{log_seq_str}\n\n"
            f"### Output:\nVerdict: "
        )
        inputs = tokenizer(prompt, return_tensors="pt", max_length=512,truncation=True).to("cuda")
        outputs = model.generate(
            **inputs,
            max_new_tokens=200,
            do_sample=False,
            temperature=0.0
        )
        full_output = tokenizer.decode(outputs[0], skip_special_tokens=True)
        verdict = "Verdict: " + full_output.split("### Output:")[-1].replace("Verdict: ", "").strip()
        finals.append({
            "seq_id": entry["sequence_id"],
            "log_seq": log_seq_str,
            "anomaly_score": entry["anomaly_score"],
            "llm_verdict": verdict
        })
        gc.collect()
        torch.cuda.empty_cache()

  0%|          | 0/100 [00:00<?, ?it/s]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  1%|          | 1/100 [00:25<41:30, 25.15s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  2%|▏         | 2/100 [00:47<38:34, 23.62s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  3%|▎         | 3/100 [01:08<36:06, 22.33s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  4%|▍         | 4/100 [01:30<35:16, 22.05s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  5%|▌         | 5/100 [01:43<29:56, 18.92s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  6%|▌         | 6/100 [01:53<24:51, 15.86s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  7%|▋         | 7/100 [02:14<27:29, 17.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  8%|▊         | 8/100 [02:28<25:01, 16.32s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
  9%|▉         | 9/100 [02:39<22:20, 14.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 10%|█         | 10/100 [02:50<20:30, 13.68s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 11%|█         | 11/100 [03:09<22:20, 15.07s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 12%|█▏        | 12/100 [03:21<21:00, 14.32s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 13%|█▎        | 13/100 [03:35<20:35, 14.20s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 14%|█▍        | 14/100 [03:49<20:09, 14.06s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 15%|█▌        | 15/100 [04:03<20:00, 14.13s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 16%|█▌        | 16/100 [04:17<19:47, 14.14s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 17%|█▋        | 17/100 [04:31<19:25, 14.04s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 18%|█▊        | 18/100 [04:45<19:08, 14.01s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 19%|█▉        | 19/100 [04:59<18:51, 13.97s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 20%|██        | 20/100 [05:13<18:35, 13.95s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 21%|██        | 21/100 [05:27<18:16, 13.89s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 22%|██▏       | 22/100 [05:40<18:04, 13.90s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 23%|██▎       | 23/100 [05:55<17:55, 13.97s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 24%|██▍       | 24/100 [06:15<20:10, 15.92s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 25%|██▌       | 25/100 [06:36<21:40, 17.33s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 26%|██▌       | 26/100 [06:56<22:23, 18.16s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 27%|██▋       | 27/100 [07:10<20:38, 16.97s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 28%|██▊       | 28/100 [07:24<19:19, 16.11s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 29%|██▉       | 29/100 [07:38<18:17, 15.45s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 30%|███       | 30/100 [07:52<17:28, 14.98s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 31%|███       | 31/100 [08:06<16:54, 14.71s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 32%|███▏      | 32/100 [08:20<16:22, 14.45s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 33%|███▎      | 33/100 [08:34<16:00, 14.33s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 34%|███▍      | 34/100 [08:48<15:41, 14.26s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 35%|███▌      | 35/100 [09:09<17:36, 16.25s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 36%|███▌      | 36/100 [09:30<18:46, 17.60s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 37%|███▋      | 37/100 [09:50<19:15, 18.34s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 38%|███▊      | 38/100 [10:04<17:45, 17.19s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 39%|███▉      | 39/100 [10:18<16:31, 16.26s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 40%|████      | 40/100 [10:32<15:32, 15.54s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 41%|████      | 41/100 [10:46<14:48, 15.06s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 42%|████▏     | 42/100 [11:00<14:14, 14.73s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 43%|████▎     | 43/100 [11:14<13:45, 14.49s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 44%|████▍     | 44/100 [11:28<13:19, 14.27s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 45%|████▌     | 45/100 [11:42<12:58, 14.15s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 46%|████▌     | 46/100 [11:56<12:43, 14.13s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 47%|████▋     | 47/100 [12:10<12:29, 14.14s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 48%|████▊     | 48/100 [12:24<12:10, 14.05s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 49%|████▉     | 49/100 [12:43<13:24, 15.78s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 50%|█████     | 50/100 [13:04<14:23, 17.26s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 51%|█████     | 51/100 [13:25<14:55, 18.28s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 52%|█████▏    | 52/100 [13:39<13:33, 16.95s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
 53%|█████▎    | 53/100 [13:53<12:33, 16.03s/it]Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.

In [47]:
with open(output_file, 'w') as f:
    json.dump(finals, f, indent=4)